/**
 * 錯誤代碼枚舉
 */
export enum ErrorCode {
  // 通用錯誤
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // 認證錯誤
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Bitfinex 錯誤
  BITFINEX_API_ERROR = 'BITFINEX_API_ERROR',
  BITFINEX_AUTH_ERROR = 'BITFINEX_AUTH_ERROR',

  // 策略錯誤
  STRATEGY_NOT_FOUND = 'STRATEGY_NOT_FOUND',
  STRATEGY_INVALID_PARAMS = 'STRATEGY_INVALID_PARAMS',
}

